Mappings:
  RegionMap:
    eu-west-3:
      AMI: ami-0f15e0a4c8d3ee5fe # Amazon Linux AMI in Paris
      CITY: Paris
    ap-northeast-1:
      AMI: ami-072bfb8ae2c884cc4 # Amazon Linux AMI in Tokyo
      CITY: Tokyo
    eu-central-1:
      AMI: ami-076309742d466ad69 # Amazon Linux AMI in Frankfurt 
      CITY: Frankfurt
Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId:
        Fn::FindInMap:
        - RegionMap
        - !Ref AWS::Region
        - AMI
      SecurityGroups: 
        - !Ref MySecurityGroup
      Tags:
        - Key: "Organization Unit"
          Value: Development
        - Key: "Project"
          Value: CloudFormation Intro
        - Key: "Name"
          Value: !Join 
            - ""
            - - "EC2 Instance for "
              - !Ref AWS::Region
        - Key: "City"
          Value: !FindInMap [RegionMap, !Ref "AWS::Region", CITY]
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0